import streamlit as st
import requests

st.set_page_config(
    page_title="Legal Document Analyzer",
    page_icon="⚖️",
    layout="wide"
)

st.title("⚖️ Legal Document Analyzer")
st.markdown("*AI-powered legal document analysis*")

# Sidebar
with st.sidebar:
    st.header("ℹ️ About")
    st.write("""
    **What it extracts:**
    - 📄 Document Summary
    - 📌 Key Clauses (Termination, Liability, Jurisdiction)
    - 🔍 Named Entities (Parties, Dates, Locations, Laws)
    """)
    
    st.header("📄 Sample Document")
    if st.button("📋 Load Sample Contract"):
        try:
            with open("data/example_contract.txt", "r") as f:
                sample_text = f.read()
            st.session_state["sample_text"] = sample_text
            st.success("✅ Sample loaded!")
        except:
            st.error("⚠️ Sample file not found")

# Main content
text = st.text_area(
    "📄 Paste legal document here:",
    height=300,
    placeholder="Paste your contract, case file, or legal text...",
    value=st.session_state.get("sample_text", "")
)

if st.button("🔍 Analyze", type="primary"):
    if text:
        with st.spinner("🧠 Analyzing legal document..."):
            try:
                response = requests.post(
                    "http://localhost:8000/analyze/",
                    data={"text": text},
                    timeout=120
                )
                
                if response.status_code == 200:
                    data = response.json()
                    
                    # Display results
                    st.subheader("📊 Analysis Results")
                    st.markdown("---")
                    
                    col1, col2 = st.columns(2)
                    
                    with col1:
                        st.subheader("📄 Summary")
                        st.info(data.get("summary", "N/A"))
                        
                        st.subheader("📌 Key Clauses")
                        st.info(data.get("clauses", "N/A"))
                    
                    with col2:
                        st.subheader("🔍 Named Entities")
                        st.info(data.get("entities", "N/A"))
                    
                    # Export
                    st.subheader("📥 Export Results")
                    
                    export_text = f"""=== LEGAL DOCUMENT ANALYSIS ===

📄 SUMMARY:
{data.get('summary', 'N/A')}

📌 KEY CLAUSES:
{data.get('clauses', 'N/A')}

🔍 NAMED ENTITIES:
{data.get('entities', 'N/A')}

================================
Generated by Legal Document Analyzer AI
"""
                    
                    st.download_button(
                        label="📥 Download Analysis",
                        data=export_text,
                        file_name="legal_analysis.txt",
                        mime="text/plain"
                    )
                else:
                    st.error(f"Error: {response.status_code}")
                    
            except requests.exceptions.ConnectionError:
                st.error("❌ Cannot connect to backend. Make sure FastAPI is running on port 8000.")
            except Exception as e:
                st.error(f"❌ Error: {str(e)}")
    else:
        st.warning("⚠️ Please paste a legal document")

# Footer
st.markdown("---")
st.caption("⚖️ Legal Document Analyzer | Powered by Gemma:2b via Ollama")